/* =====================================================
   VELMORA — Product Data Store
   ===================================================== */

const VELMORA_PRODUCTS = [
  {
    id: 1,
    name: "Noir Oud",
    tagline: "Woody · Oriental",
    gender: "men",
    type: "woody",
    price: 1299,
    size: "50ml",
    badge: "Best Seller",
    badgeType: "bestseller",
    topNotes: "Bergamot, Saffron",
    middleNotes: "Oud, Rose",
    baseNotes: "Sandalwood, Musk, Amber",
    description: "A commanding presence in every room. Noir Oud opens with a burst of bright bergamot and precious saffron, before revealing its luxurious heart of rare oud and rose. The base of warm sandalwood, musk, and amber lingers beautifully for hours.",
    related: [2, 5, 7]
  },
  {
    id: 2,
    name: "Rose Elixir",
    tagline: "Floral · Feminine",
    gender: "women",
    type: "floral",
    price: 999,
    size: "50ml",
    badge: "New",
    badgeType: "new",
    topNotes: "Pink Pepper, Peach",
    middleNotes: "Bulgarian Rose, Jasmine",
    baseNotes: "White Musk, Patchouli",
    description: "A celebration of femininity. Rose Elixir is a modern floral built around the finest Bulgarian rose absolute, supported by the playful warmth of peach and the depth of white musk. Effortlessly romantic.",
    related: [4, 6, 9]
  },
  {
    id: 3,
    name: "Blanc Ether",
    tagline: "Fresh · Unisex",
    gender: "unisex",
    type: "fresh",
    price: 799,
    size: "50ml",
    badge: null,
    topNotes: "Citrus, Sea Salt",
    middleNotes: "Iris, Violet",
    baseNotes: "Cedarwood, White Musk",
    description: "Clean, crisp, and effortlessly sophisticated. Blanc Ether captures the feeling of a cool ocean morning — citrus and sea salt give way to soft iris before settling into a luminous cedarwood base.",
    related: [5, 7, 1]
  },
  {
    id: 4,
    name: "Velvet Amber",
    tagline: "Oriental · Warm",
    gender: "women",
    type: "woody",
    price: 1199,
    size: "50ml",
    badge: "Best Seller",
    badgeType: "bestseller",
    topNotes: "Mandarin, Cardamom",
    middleNotes: "Amber, Ylang-ylang",
    baseNotes: "Vanilla, Tonka Bean",
    description: "Sensuous and enveloping. Velvet Amber is a rich oriental built for those who love warmth and depth. The interplay of cardamom, amber, and vanilla creates an intoxicating warmth that is wholly unforgettable.",
    related: [2, 8, 9]
  },
  {
    id: 5,
    name: "Cedar Storm",
    tagline: "Woody · Fresh",
    gender: "men",
    type: "woody",
    price: 899,
    size: "50ml",
    badge: null,
    topNotes: "Grapefruit, Black Pepper",
    middleNotes: "Cedarwood, Juniper",
    baseNotes: "Vetiver, Oakmoss",
    description: "Raw, natural, powerful. Cedar Storm channels the spirit of wild forests and open skies. Black pepper and grapefruit cut through the air before cedarwood and vetiver ground this fragrance in nature's purest expression.",
    related: [1, 3, 7]
  },
  {
    id: 6,
    name: "Sakura Dew",
    tagline: "Floral · Fresh",
    gender: "women",
    type: "floral",
    price: 599,
    size: "50ml",
    badge: "New",
    badgeType: "new",
    topNotes: "Green Tea, Yuzu",
    middleNotes: "Cherry Blossom, Magnolia",
    baseNotes: "Sandalwood, Light Musk",
    description: "Delicate and luminous. Sakura Dew is a whisper of spring — green tea and yuzu float over a heart of cherry blossom and magnolia, resting on a barely-there sandalwood base. Light, airy, and utterly lovely.",
    related: [2, 4, 9]
  },
  {
    id: 7,
    name: "Aqua Libre",
    tagline: "Aquatic · Fresh",
    gender: "unisex",
    type: "fresh",
    price: 699,
    size: "50ml",
    badge: null,
    topNotes: "Sea Spray, Lemon",
    middleNotes: "Marine Accord, Lavender",
    baseNotes: "Amberwood, Musk",
    description: "Freedom in a bottle. Aqua Libre is the scent of open water — invigorating sea spray and lemon open into a calming lavender marine heart, anchored by warm amberwood for depth that lasts all day.",
    related: [3, 5, 8]
  },
  {
    id: 8,
    name: "Gold Opus",
    tagline: "Oriental · Spicy",
    gender: "men",
    type: "woody",
    price: 1499,
    size: "50ml",
    badge: "Premium",
    badgeType: "bestseller",
    topNotes: "Bergamot, Elemi",
    middleNotes: "Rose, Incense, Oud",
    baseNotes: "Labdanum, Ambergris, Musk",
    description: "The pinnacle of our collection. Gold Opus is a rare masterpiece — complex, layered, and profoundly compelling. A fragrance reserved for those who understand that true luxury is felt, not merely seen.",
    related: [1, 4, 5]
  },
  {
    id: 9,
    name: "Fleur Douce",
    tagline: "Floral · Sweet",
    gender: "women",
    type: "floral",
    price: 499,
    size: "50ml",
    badge: null,
    topNotes: "Raspberry, Pear",
    middleNotes: "Peony, Freesia",
    baseNotes: "Musk, Cashmere Wood",
    description: "Playful yet refined. Fleur Douce opens with a burst of fresh raspberry and pear before blooming into a soft floral heart of peony and freesia. The cashmere wood base gives it a smooth, lingering warmth.",
    related: [2, 6, 4]
  },
  {
    id: 10,
    name: "Terra Firma",
    tagline: "Earthy · Unisex",
    gender: "unisex",
    type: "woody",
    price: 849,
    size: "50ml",
    badge: null,
    topNotes: "Cardamom, Ginger",
    middleNotes: "Leather, Geranium",
    baseNotes: "Tobacco, Dark Amber",
    description: "Grounded and modern. Terra Firma is for those who walk with intention. Cardamom and ginger ignite before leather and geranium unfold, settling into a smoky tobacco and dark amber base that marks your passage.",
    related: [3, 7, 8]
  },
  {
    id: 11,
    name: "Lumière Blanche",
    tagline: "Powdery · Soft",
    gender: "women",
    type: "floral",
    price: 749,
    size: "50ml",
    badge: null,
    topNotes: "Aldehydes, Neroli",
    middleNotes: "Iris, Violet",
    baseNotes: "Musk, Vetiver, Sandalwood",
    description: "A timeless whisper. Lumière Blanche is clean, powdery elegance — the kind worn by those who prefer their presence to linger gently, not loudly. An hommage to the great white florals of the golden age of perfumery.",
    related: [2, 6, 9]
  },
  {
    id: 12,
    name: "Midnight Patchouli",
    tagline: "Dark · Woody",
    gender: "unisex",
    type: "woody",
    price: 1099,
    size: "50ml",
    badge: "Best Seller",
    badgeType: "bestseller",
    topNotes: "Black Currant, Mandarin",
    middleNotes: "Patchouli, Rose",
    baseNotes: "Dark Chocolate, Benzoin",
    description: "Seductive and mysterious. Midnight Patchouli is a dark, sensuous journey — tart black currant and sweet mandarin slowly give way to earthy patchouli and rose, dissolving into a decadent accord of dark chocolate and benzoin.",
    related: [8, 1, 10]
  }
];

// Helper to format price in INR
function formatPrice(price) {
  return '₹' + price.toLocaleString('en-IN');
}
